### ISSUE TITLE
(Documentation) Does this plugin add use strict or not?

### ISSUE THREAD

**Issue by davidshepherd7** [TrySound/babel-plugin-iife-wrap#3]
I noticed that in your [tests](https://github.com/TrySound/babel-plugin-iife-wrap/blob/master/test.js) you expect `use strict` to have been added to the result, but this isn't mentioned in the readme.

**Comment by TrySound** [comment]
@davidshepherd7 Test is the best doc :) Would you like to send a PR with mention?

**Comment by davidshepherd7** [comment]
I would but I'm not entirely sure what it actually does do.

**Comment by TrySound** [comment]
According tests it adds 'use strict'; if it is not present.

**Comment by davidshepherd7** [comment]
Is that unconditionally, or with a certain configuration? Do you need to install an additional plugin to get the use strict?

**Comment by TrySound** [comment]
@davidshepherd7 It inherits strict mode plugin, so you don't need. And yes it's unconditionally.
